import React from 'react';
import {
  Bot, Clapperboard, Wrench, ClipboardCheck, Search, Library, ListChecks,
  Binary, Database, MessageCircle, Presentation, Video, Network, Gamepad2,
  Mic, PenTool, PieChart, Mic2, Activity, FlaskConical, HeartHandshake,
  Music, Globe, PlusCircle, Award, FileText, Podcast, BookOpen, Sparkles,
  Brain, VenetianMask, Pipette, Flower2, MapPin, Share2, Code2, Book,
  ClipboardList, Users, LayoutTemplate, Glasses
} from 'lucide-react';
import { DeliveryModeType } from './types';

export const DELIVERY_MODE_ICONS: Record<DeliveryModeType, React.ReactNode> = {
  [DeliveryModeType.READING]: <BookOpen className="w-5 h-5" />,
  [DeliveryModeType.PRESENTATION]: <Presentation className="w-5 h-5" />,
  [DeliveryModeType.AI]: <Bot className="w-5 h-5" />,
  [DeliveryModeType.ANIMATION]: <Clapperboard className="w-5 h-5" />,
  [DeliveryModeType.APPLICATION]: <Wrench className="w-5 h-5" />,
  [DeliveryModeType.ASSESSMENT]: <ClipboardCheck className="w-5 h-5" />,
  [DeliveryModeType.CASE_STUDY]: <Search className="w-5 h-5" />,
  [DeliveryModeType.CATALOG]: <Library className="w-5 h-5" />,
  [DeliveryModeType.CHECKLIST]: <ListChecks className="w-5 h-5" />,
  [DeliveryModeType.DATA_POINTS]: <Binary className="w-5 h-5" />,
  [DeliveryModeType.DATA_SET]: <Database className="w-5 h-5" />,
  [DeliveryModeType.DISCUSSION]: <MessageCircle className="w-5 h-5" />,
  [DeliveryModeType.FACILITATION]: <Presentation className="w-5 h-5" />,
  [DeliveryModeType.FILM_VIDEO]: <Video className="w-5 h-5" />,
  [DeliveryModeType.FLOWCHART]: <Network className="w-5 h-5" />,
  [DeliveryModeType.GAMIFICATION]: <Gamepad2 className="w-5 h-5" />,
  [DeliveryModeType.GUEST_SPEAKER]: <Mic className="w-5 h-5" />,
  [DeliveryModeType.HANDS_ON]: <PenTool className="w-5 h-5" />,
  [DeliveryModeType.INFOGRAPHIC]: <PieChart className="w-5 h-5" />,
  [DeliveryModeType.INTERVIEW]: <Mic2 className="w-5 h-5" />,
  [DeliveryModeType.KINESTHETIC]: <Activity className="w-5 h-5" />,
  [DeliveryModeType.LAB_WORK]: <FlaskConical className="w-5 h-5" />,
  [DeliveryModeType.MENTORING]: <HeartHandshake className="w-5 h-5" />,
  [DeliveryModeType.MUSIC]: <Music className="w-5 h-5" />,
  [DeliveryModeType.ONLINE_REMOTE]: <Globe className="w-5 h-5" />,
  [DeliveryModeType.OTHER]: <PlusCircle className="w-5 h-5" />,
  [DeliveryModeType.PMP_EXAM]: <Award className="w-5 h-5" />,
  [DeliveryModeType.PMI_CONTENT]: <FileText className="w-5 h-5" />,
  [DeliveryModeType.PODCAST]: <Podcast className="w-5 h-5" />, // Lucide'da harbi Podcast ikonu var!
  [DeliveryModeType.REALITY]: <Sparkles className="w-5 h-5" />,
  [DeliveryModeType.REFLECTION]: <Brain className="w-5 h-5" />,
  [DeliveryModeType.ROLE_PLAYING]: <VenetianMask className="w-5 h-5" />, // Tiyatro/Rol maskesi daha şık durur
  [DeliveryModeType.SAMPLE]: <Pipette className="w-5 h-5" />,
  [DeliveryModeType.SCENT]: <Flower2 className="w-5 h-5" />, // Koku için çiçek mantıklı oldu
  [DeliveryModeType.SITE_VISIT]: <MapPin className="w-5 h-5" />,
  [DeliveryModeType.SOCIAL_MEDIA]: <Share2 className="w-5 h-5" />,
  [DeliveryModeType.SOFTWARE]: <Code2 className="w-5 h-5" />,
  [DeliveryModeType.STORYTELLING]: <Book className="w-5 h-5" />,
  [DeliveryModeType.SURVEY]: <ClipboardList className="w-5 h-5" />,
  [DeliveryModeType.TEAMWORK]: <Users className="w-5 h-5" />,
  [DeliveryModeType.TEMPLATE]: <LayoutTemplate className="w-5 h-5" />,
  [DeliveryModeType.VR]: <Glasses className="w-5 h-5" />,
};

export const DELIVERY_MODE_LABELS: Record<DeliveryModeType, string> = {
  [DeliveryModeType.READING]: 'READING',
  [DeliveryModeType.PRESENTATION]: 'PRESENTATION',
  [DeliveryModeType.AI]: 'AI',
  [DeliveryModeType.ANIMATION]: 'ANIMATION',
  [DeliveryModeType.APPLICATION]: 'APPLICATION',
  [DeliveryModeType.ASSESSMENT]: 'ASSESSMENT',
  [DeliveryModeType.CASE_STUDY]: 'CASE_STUDY',
  [DeliveryModeType.CATALOG]: 'CATALOG',
  [DeliveryModeType.CHECKLIST]: 'CHECKLIST',
  [DeliveryModeType.DATA_POINTS]: 'DATA_POINTS',
  [DeliveryModeType.DATA_SET]: 'DATA_SET',
  [DeliveryModeType.DISCUSSION]: 'DISCUSSION',
  [DeliveryModeType.FACILITATION]: 'FACILITATION',
  [DeliveryModeType.FILM_VIDEO]: 'FILM_VIDEO',
  [DeliveryModeType.FLOWCHART]: 'FLOWCHART',
  [DeliveryModeType.GAMIFICATION]: 'GAMIFICATION',
  [DeliveryModeType.GUEST_SPEAKER]: 'GUEST_SPEAKER',
  [DeliveryModeType.HANDS_ON]: 'HANDS_ON',
  [DeliveryModeType.INFOGRAPHIC]: 'INFOGRAPHIC',
  [DeliveryModeType.INTERVIEW]: 'INTERVIEW',
  [DeliveryModeType.KINESTHETIC]: 'KINESTHETIC',
  [DeliveryModeType.LAB_WORK]: 'LAB_WORK',
  [DeliveryModeType.MENTORING]: 'MENTORING',
  [DeliveryModeType.MUSIC]: 'MUSIC',
  [DeliveryModeType.ONLINE_REMOTE]: 'ONLINE_REMOTE',
  [DeliveryModeType.PMP_EXAM]: 'PMP_EXAM',
  [DeliveryModeType.PMI_CONTENT]: 'PMI_CONTENT',
  [DeliveryModeType.PODCAST]: 'PODCAST',
  [DeliveryModeType.REALITY]: 'REALITY',
  [DeliveryModeType.REFLECTION]: 'REFLECTION',
  [DeliveryModeType.ROLE_PLAYING]: 'ROLE_PLAYING',
  [DeliveryModeType.SAMPLE]: 'SAMPLE',
  [DeliveryModeType.SCENT]: 'SCENT',
  [DeliveryModeType.SITE_VISIT]: 'SITE_VISIT',
  [DeliveryModeType.SOCIAL_MEDIA]: 'SOCIAL_MEDIA',
  [DeliveryModeType.SOFTWARE]: 'SOFTWARE',
  [DeliveryModeType.STORYTELLING]: 'STORYTELLING',
  [DeliveryModeType.SURVEY]: 'SURVEY',
  [DeliveryModeType.TEAMWORK]: 'TEAMWORK',
  [DeliveryModeType.TEMPLATE]: 'TEMPLATE',
  [DeliveryModeType.VR]: 'VR',
  [DeliveryModeType.OTHER]: 'OTHER',
};

export const SDGS_LIST = [
  "1. No Poverty",
  "2. Zero Hunger",
  "3. Good Health and Well-being",
  "4. Quality Education",
  "5. Gender Equality",
  "6. Clean Water and Sanitation",
  "7. Affordable and Clean Energy",
  "8. Decent Work and Economic Growth",
  "9. Industry, Innovation and Infrastructure",
  "10. Reduced Inequalities",
  "11. Sustainable Cities and Communities",
  "12. Responsible Consumption and Production",
  "13. Climate Action",
  "14. Life Below Water",
  "15. Life on Land",
  "16. Peace, Justice and Strong Institutions",
  "17. Partnerships for the Goals"
];
